In [ ]:
# %load train.py
import tensorflow as tf
import numpy as np
import os
import cv2
import dense_net

import anchor_op
from xml_op import *
%matplotlib inline

anchor_num = 3
a_num = 1
ratio_num = 3
stride=np.array([7,14,28,56])
anchor_size=np.array([64,32,16,8])
ratio = np.array([[1,1],[1,2],[2,1]])

rpn_ckpts = './checkpoint2_dir'
rpn_adam_meta = './checkpoint2_dir/MyModel'

roi_ckpts = './roi_ck2'
roi_adam_meta = './roi_ck2/MyModel'
   

def check_enviroment(path):
    if(not os.path.exists(path)):
        os.mkdir(path)
        print('create dir')
    else:
        print('already exist')
        
def show_img(img):
    plt.imshow(img)
    plt.show()

def cal_l1_loss(real_box_dx,pre_box,is_real_box,ll1,ll2,ll3):
    j1 = tf.add(real_box_dx,(-1)*pre_box)
    j2 = tf.cast(tf.less(tf.abs(j1),ll1),tf.float32)
    j3 = is_real_box*((j2)*(ll2*j1*j1)+(1.0-j2)*(tf.abs(j1)-ll3))
    j4 = tf.reduce_sum(j3)
    return j4,j3

def region_proposal(anchor_ut,sort_id,sort_score,dx_box_loc,r_box_loc):
    rpn_anchor = anchor_ut.get_best_anchor(sort_id,sort_score,dx_box_loc)
    #print(rpn_anchor)
    rpn_anchor_index = anchor_ut.py_cpu_nms(rpn_anchor)
    dx_box_loc = rpn_anchor[rpn_anchor_index,0:4]
    #print(dx_box_loc)
    #print(dx_box_loc.shape)
    fg_bg_check,real_fg_bg_value,box_index,is_anchor = anchor_ut.collect_roi_fg_bg(dx_box_loc,r_box_loc,pos_iou=0.5,neg_iou=0.1,max_anchor=128)
    #print(fg_bg_check)
    #print(real_fg_bg_value)
    #print(is_anchor)
    rpn_box = np.zeros([rpn_anchor_index.shape[0],6])
    for i in range(fg_bg_check.shape[1]):
        if(fg_bg_check[0][i]!=0):
            x1,y1,x2,y2 = dx_box_loc[i]
            rpn_box[i,:4] = x1,y1,x2,y2
            
            w = x2-x1
            h = y2-y1
            feature_num = 3+int(np.log2((np.sqrt(w*h)/224)))
            if(feature_num<0):
                feature_num = 0
            if(real_fg_bg_value[0][i][0]==1):
                rpn_box[i][4] = feature_num
                rpn_box[i][5] = 0    
            else:
                rpn_box[i][4] = feature_num
                rpn_box[i][5] = 1
            
    #print(rpn_box[:,5])
    real_fg_bg_value = np.squeeze(real_fg_bg_value)
    fg_bg_check = np.squeeze(fg_bg_check)
    #print(real_fg_bg_value.shape)
    return rpn_box,fg_bg_check,real_fg_bg_value,box_index,is_anchor

def rpn_train():
    train_data = read_xml('./outputs')
    #train_data = read_xml('./xml_test')
    '''
    img = cv2.imread('test.jpg')
    r_img = np.reshape(img,(-1,224,224,3))
    r_box = np.reshape(np.array([[78,54,148,173]],dtype=np.float),(-1,4))
    '''
    ds = dense_net.Dense_net(224,3,10,24,0.5)
    x = ds.x
    
    pre_fg,pre_fg_score = ds.all_fg,ds.all_fg_score
    pre_box_dx = ds.all_box
    
    sort_fg_index,sort_fg_score = ds.sort_fg_score()
    
    real_fg = tf.placeholder(tf.float32,[None,None,2])
    is_real_fg = tf.placeholder(tf.float32,[None,None])
    fg_num = tf.placeholder(tf.float32)
    
    real_box_dx = tf.placeholder(tf.float32,[None,None,4])
    is_real_box_dx = tf.placeholder(tf.float32,[None,None,4])
    box_num = tf.placeholder(tf.float32)
    
    fg_loss = tf.nn.sparse_softmax_cross_entropy_with_logits(
                                    labels=tf.argmax(real_fg,axis=2),logits=pre_fg)

    fg_loss = tf.reduce_sum(tf.multiply(fg_loss,is_real_fg))
    fg_loss = fg_loss/fg_num
    box_loss,j1 = cal_l1_loss(real_box_dx,pre_box_dx,is_real_box_dx,1.0,0.5,0.5)
    box_loss = (box_loss/box_num)*5
    box_loss = tf.clip_by_value(box_loss,1e-10,box_loss)
    rpn_total_loss = fg_loss+box_loss
    
    global_step = tf.get_variable('global_step', [], dtype=tf.int32,
                                  initializer=tf.constant_initializer(0), trainable=False)

    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    with tf.name_scope('opt'):
        #opt = tf.train.AdamOptimizer(1e-3,name='optimizer')
        #opt = tf.train.GradientDescentOptimizer(5e-3,name='optimizer')
        opt = tf.train.MomentumOptimizer(1e-4,0.9,name='optimizer')
        with tf.control_dependencies(update_ops):
            grads = opt.compute_gradients(rpn_total_loss)
            train_op = opt.apply_gradients(grads, global_step=global_step)
        #tf.summary.scalar('opti', opt)
    
    anchor_ut = anchor_op.anchor_util(stride,anchor_size)
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        
        ########  save
        var_list = tf.trainable_variables()
        if global_step is not None:
            var_list.append(global_step)
        g_list = tf.global_variables()
        bn_moving_vars = [g for g in g_list if 'moving_mean' in g.name]
        bn_moving_vars += [g for g in g_list if 'moving_variance' in g.name]
        var_list += bn_moving_vars
        saver = tf.train.Saver(var_list=var_list,max_to_keep=5)
        ########
        
        if tf.train.latest_checkpoint(rpn_ckpts) is not None:
            saver.restore(sess, tf.train.latest_checkpoint(rpn_ckpts))
            #saver = tf.train.import_meta_graph('./checkpoint1_dir/MyModel-3250.meta')
        else:
            assert 'can not find checkpoint folder path!'
        
        
        for i in range(1000):
            print('-----')
            
            ba_x = i%15
            print(train_data[ba_x])
            img,r_box = decode_xml(train_data[ba_x])
            r_img = img[np.newaxis,:,:,:]
            
            #print(r_img.shape)
            
            pf_value,pf_score,dx_box,sort_id,sort_score,td = sess.run([pre_fg,pre_fg_score,pre_box_dx,
                                                 sort_fg_index,sort_fg_score,ds.dense4],feed_dict={x:r_img})
    
            dx_box_loc = anchor_ut.get_dx_box(dx_box[0])
            
            fg_bg_check,real_fg_bg_value,box_index,is_anchor = anchor_ut.collect_fg_bg(dx_box_loc,r_box)
            
            dx_anchor_value,is_dx_box,is_box = anchor_ut.collect_anchor_dx(dx_box,box_index,real_fg_bg_value,r_box)
                          
            
            fg_ls,box_ls,fg_rank,_= sess.run([fg_loss,box_loss,sort_fg_index,train_op],feed_dict={x:r_img,
                                               real_box_dx:dx_anchor_value,is_real_box_dx:is_dx_box,box_num:is_box,
                                               real_fg:real_fg_bg_value,is_real_fg:fg_bg_check,fg_num:is_anchor
                                               })
                    
            if(i%1==0):
                for j in range(pf_score.shape[1]):
                    if(real_fg_bg_value[0][j][0]==1):
                        rank = 0
                        for k in range(fg_rank.shape[0]):
                            if(fg_rank[k]==j):
                                rank = k
                        #print('high',pf_score[0][fg_rank[0]])
                        #print('low',pf_score[0][fg_rank[-1]])
                        print('fg_score',pf_score[0][j],'rank',rank,' id',j)
                        print(fg_ls,box_ls)
                        
            if(i%50==0 and i!=0):
                saver.save(sess,rpn_adam_meta,global_step=i) 
                
def roi_train():
    train_data = read_xml('./outputs')
    '''
    img = cv2.imread('test.jpg')
    r_img = np.reshape(img,(-1,224,224,3))
    r_box = np.reshape(np.array([[78,54,148,173],[28,12,64,99]],dtype=np.float),(-1,4))
    '''
    ds = dense_net.Dense_net(224,3,10,24,0.5)
    x = ds.x
    
    pre_fg,pre_fg_score = ds.all_fg,ds.all_fg_score
    pre_box_dx = ds.all_box
    
    sort_fg_index,sort_fg_score = ds.sort_fg_score()
       
    roi_cls_score,roi_cls_score_p,roi_box_dx = ds.cls_score,ds.cls_score_p,ds.final_box
    #print(roi_cls_score)
    roi_feature_map = ds.roi_feature_map
    roi_cls = tf.placeholder(tf.float32,[None,2])
    roi_is_fg = tf.placeholder(tf.float32,[None])
    roi_fg_num = tf.placeholder(tf.float32)
    '''
    rpn_boxes = tf.placeholder(tf.float32,[None,4])
    rpn_num = tf.placeholder(tf.int32)
    roi_feature_2 = ds.roi_pooling_2(rpn_boxes,rpn_num)
    print(roi_feature_2)
    '''
    real_box_dx = tf.placeholder(tf.float32,[None,None,4])
    is_real_box_dx = tf.placeholder(tf.float32,[None,None,4])
    box_num = tf.placeholder(tf.float32)
    
    box_loss,j1 = cal_l1_loss(real_box_dx,ds.final_box,is_real_box_dx,1.0,0.5,0.5)
    box_loss = (box_loss/box_num)
    box_loss = tf.clip_by_value(box_loss,1e-10,box_loss)


    cls_loss =  tf.nn.sparse_softmax_cross_entropy_with_logits(
                                    labels=tf.argmax(roi_cls,axis=1),logits=roi_cls_score)
    cls_loss = tf.reduce_sum(tf.multiply(cls_loss,roi_is_fg))
    cls_loss = cls_loss/roi_fg_num
    
    roi_total_loss = cls_loss+box_loss
    
    global_step = tf.get_variable('global_step', [], dtype=tf.int32,
                                  initializer=tf.constant_initializer(0), trainable=False)

    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    
    with tf.name_scope('roi_opt'):
        #opt = tf.train.AdamOptimizer(1e-3,name='optimizer')
        #opt = tf.train.GradientDescentOptimizer(5e-3,name='optimizer')
        opt = tf.train.MomentumOptimizer(1e-4,0.9,name='optimizer')
        with tf.control_dependencies(update_ops):
            grads = opt.compute_gradients(roi_total_loss)
            train_op = opt.apply_gradients(grads, global_step=global_step)
        #tf.summary.scalar('opti', opt)
    
    anchor_ut = anchor_op.anchor_util(stride,anchor_size)
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        
        ########  saves
        var_list = tf.trainable_variables()
        if global_step is not None:
            var_list.append(global_step)
        g_list = tf.global_variables()
        bn_moving_vars = [g for g in g_list if 'moving_mean' in g.name]
        bn_moving_vars += [g for g in g_list if 'moving_variance' in g.name]
        var_list += bn_moving_vars
        saver = tf.train.Saver(var_list=var_list,max_to_keep=5)
        ########
        
        if tf.train.latest_checkpoint(rpn_ckpts) is not None:
            saver.restore(sess, tf.train.latest_checkpoint(rpn_ckpts))
        else:
            assert 'can not find checkpoint folder path!'
        
        
        for i in range(1000):
            print('-----')
            ba_x = i%15
            #print(train_data[ba_x])
            img,r_box = decode_xml(train_data[ba_x])
            r_img = img[np.newaxis,:,:,:]
            
            pf_value,pf_score,dx_box,sort_id,sort_score = sess.run([pre_fg,pre_fg_score,pre_box_dx,
                                                 sort_fg_index,sort_fg_score],feed_dict={x:r_img})
    
            dx_box_loc = anchor_ut.get_dx_box(dx_box[0])
            #print(dx_box_loc)
            if(i<=60):
                rpn_box,roi_fg_bg_check,roi_real_fg_bg_value,roi_box_index,roi_is_anchor = region_proposal(anchor_ut,sort_id,sort_score,dx_box_loc,r_box)

                roi_feature,cls = ds.roi_pooling(rpn_box)
                r_feature = sess.run(roi_feature,feed_dict={x:r_img})

                rcs,rcsp,rdx = sess.run([roi_cls_score,roi_cls_score_p,roi_box_dx],feed_dict={roi_feature_map:r_feature})
                print(rdx[0],rpn_box[0],roi_box_dx)

                dx_anchor_value,is_dx_box,is_box = anchor_ut.collect_anchor_dx(rpn_box[np.newaxis,:,:4],
                                                                        roi_box_index,roi_real_fg_bg_value[np.newaxis,:,:],r_box,rpn_box[:,:4])
            
            else:
                ####
                rpn_box = anchor_ut.region_proposal_2(sort_id,sort_score,dx_box_loc)
                roi_feature = ds.roi_pooling_1(rpn_box)
                r_feature = sess.run(roi_feature,feed_dict={x:r_img})
                rcs,rcsp,rdx = sess.run([roi_cls_score,roi_cls_score_p,roi_box_dx],feed_dict={roi_feature_map:r_feature})
                print(rdx[0],rpn_box[0])
                dx_box_loc2 = anchor_ut.get_dx_box(rdx,rpn_box[:,:4])
                roi_fg_bg_check,roi_real_fg_bg_value,roi_box_index,roi_is_anchor = anchor_ut.collect_roi_fg_bg(dx_box_loc2,r_box,pos_iou=0.5,neg_iou=0.1,max_anchor=128)
                dx_anchor_value,is_dx_box,is_box = anchor_ut.collect_anchor_dx(dx_box_loc2,
                                                                        roi_box_index,roi_real_fg_bg_value,r_box,rpn_box[:,:4])
                roi_real_fg_bg_value = np.reshape(roi_real_fg_bg_value,(-1,2))
                roi_fg_bg_check = roi_fg_bg_check[0]
                ####
            
            '''
            #print(rpn_box)
            #r_feature = sess.run(roi_feature,feed_dict={rpn_boxes:rpn_box[np.newaxis,:,:],rpn_num:rpn_box.shape[0]})
            r = sess.run(roi_feature_2,feed_dict={rpn_boxes:rpn_box[:,:4],rpn_num:rpn_box.shape[0],x:r_img})
            print(r.shape,r[0][0][0][0:10])
            #print(dsf)
            '''
            for j in range(roi_real_fg_bg_value.shape[0]):
                if(roi_real_fg_bg_value[j][0]==1):
                    print('is fg',rcsp[j])
                '''     
                    im = img.copy()
                    x1,y1,x2,y2 = rpn_box[j,:4]

                        cv2.rectangle(im,(int(x1),int(y1)),(int(x2),int(y2)), (0, 255, 0), 2)
                        show_img(im)
                else:
                    print(rcsp[j])
                    cv2.rectangle(im,(int(x1),int(y1)),(int(x2),int(y2)), (0, 255, 0), 2)
                    show_img(im)
                '''   
            
            #print(roi_is_anchor)
            #print(roi_real_fg_bg_value.shape,roi_fg_bg_check.shape,roi_is_anchor)
            #print(is_dx_box.shape,dx_anchor_value.shape,is_dx_box.shape,is_box)
            cls_ls,box_ls,_ = sess.run([cls_loss,box_loss,train_op],
                                        feed_dict={roi_cls:roi_real_fg_bg_value,roi_is_fg:roi_fg_bg_check,
                                           roi_fg_num:roi_is_anchor,roi_feature_map:r_feature,x:r_img,
                                           real_box_dx:dx_anchor_value,is_real_box_dx:is_dx_box,box_num:is_box})
            
            print(cls_ls,box_ls)
                        
            if(i%100==0 and i!=0):
                saver.save(sess,roi_adam_meta,global_step=i) 


if(__name__=='__main__'):
    #rpn_train()
    roi_train()

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Instructions for updating:
Use the retry module or similar alternatives.
Tensor("dense_net/resnext/max_pooling2d/MaxPool:0", shape=(?, 56, 56, 64), dtype=float32)
Tensor("dense_net/resnext/Relu_17:0", shape=(?, 56, 56, 64), dtype=float32)
Tensor("dense_net/resnext/Relu_34:0", shape=(?, 28, 28, 128), dtype=float32)
Tensor("dense_net/resnext/Relu_51:0", shape=(?, 14, 14, 256), dtype=float32)
Tensor("dense_net/resnext/Relu_68:0", shape=(?, 7, 7, 512), dtype=float32)
(<tf.Tensor 'concat:0' shape=(?, 12495, 2) dtype=float32>, <tf.Tensor 'concat_1:0' shape=(?, 12495, 2) dtype=float32>, <tf.Tensor 'concat_2:0' shape=(?, 12495, 4) dtype=float32>)
Tensor("flatten/Reshape:0", shape=(?, 12544), dtype=float32)
(?, 12495, 2)
INFO:tensorflow:Restoring parameters from ./checkpoint2_dir/MyModel-150
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
0.9615384615384616
0.9803921568627451
0.5173288250211328
0.9349593495934959
(4, 10)
(array([-0.96699893,  0.49325764, -0.1525035 ,  0.324655  ], dtype=float

(array([-0.01603042, -0.19174795, -0.30988416, -0.1672666 ], dtype=float32), array([151., 120., 199., 187.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.8323192 , 0.16768084], dtype=float32))
('is fg', array([0.90950716, 0.09049286], dtype=float32))
('is fg', array([0.6926705 , 0.30732945], dtype=float32))
('is fg', array([0.7794127 , 0.22058736], dtype=float32))
('is fg', array([0.8522938 , 0.14770626], dtype=float32))
(0.5851421, 0.19240817)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
0.9615384615384616
0.9803921568627451
0.5173288250211328
0.9349593495934959
(4, 10)
(array([ 0.39312127, -0.08695547, -0.16912684,  0.1099202 ], dtype=float32), array([ 87.,  35., 138., 106.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.87878793, 0.12121212], dtype=float32))
('is fg', array([0.8540716 , 0.14592837], dtype=float32))
('is fg', array([0.88772416, 0.11227585], dtype=float32))
('is fg', arra

(array([ 0.32490197,  0.16330884, -0.05141404,  0.2127503 ], dtype=float32), array([ 87.,  35., 138., 106.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.92814523, 0.07185483], dtype=float32))
('is fg', array([0.8959516 , 0.10404838], dtype=float32))
('is fg', array([0.9388205 , 0.06117947], dtype=float32))
('is fg', array([0.8397684 , 0.16023158], dtype=float32))
(0.46538547, 0.054185137)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
0.9652650822669104
1.0
0.9510657460222155
0.9660421545667447
0.9795918367346939
0.9459540161242161
(6, 13)
(array([ 0.0276326 ,  0.04409926,  0.23092076, -0.01282462], dtype=float32), array([150.,  37., 199., 104.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.812606  , 0.18739401], dtype=float32))
('is fg', array([0.9118994 , 0.08810057], dtype=float32))
('is fg', array([0.79684293, 0.20315707], dtype=float32))
('is fg', array([0.7863329 , 0.2

(array([-0.01013691,  0.02299865,  0.18265511, -0.00021379], dtype=float32), array([150.,  37., 199., 104.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.83858776, 0.1614123 ], dtype=float32))
('is fg', array([0.9343225 , 0.06567752], dtype=float32))
('is fg', array([0.80784583, 0.19215423], dtype=float32))
('is fg', array([0.8202613 , 0.17973875], dtype=float32))
('is fg', array([0.80117804, 0.19882198], dtype=float32))
('is fg', array([0.68326646, 0.3167335 ], dtype=float32))
(0.2702946, 0.045796398)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
0.9493670886075949
(1, 25)
(array([ 0.00423066, -0.06462956, -0.04616095,  0.00173052], dtype=float32), array([120.,  65., 186., 156.,   2.,   0.]), <tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 4) dtype=float32>)
('is fg', array([0.8892271 , 0.11077289], dtype=float32))
(0.32228047, 0.003985631)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 1

(array([ 0.0412893 , -0.03346354, -0.0085738 ,  0.00816549], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.596646942800789
0.8675599875350577
0.5720368081307513
(3, 23)
('is fg', array([0.9114605 , 0.08853942], dtype=float32))
('is fg', array([0.54339653, 0.45660347], dtype=float32))
('is fg', array([0.46751904, 0.53248096], dtype=float32))
(0.6510594, 0.034706872)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([ 0.1072825 , -0.2426733 , -0.04840392,  0.13665864], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.7482476635514018
0.637901019646854
0.6438415159345392
0.5358302662914051
0.6901669758812616
0.7302423603793466
0.7740524781341108
(7, 14)
('is fg', array([0.9212141 , 0.07878589], dtype=float32))
('is fg', array([0.81623095, 0.18376905], dtype=float32))
('is fg', array([0.772223, 0.227777], dtype=float32))
('is fg', array([0.83682203, 0.16317795], dtype=float32))
('is fg', array([0.84259814, 0.15740184], dtype=float32))
('is fg'

(array([ 0.08096749, -0.22691758, -0.06070757,  0.10600142], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.7577639751552795
0.6764331210191082
0.7230769230769231
0.5760473588342441
0.7413127413127413
0.7687093275488069
0.7696793002915452
(7, 14)
('is fg', array([0.9238907 , 0.07610934], dtype=float32))
('is fg', array([0.82299364, 0.17700633], dtype=float32))
('is fg', array([0.78165066, 0.21834934], dtype=float32))
('is fg', array([0.8441069 , 0.15589312], dtype=float32))
('is fg', array([0.85388875, 0.14611131], dtype=float32))
('is fg', array([0.85609233, 0.14390768], dtype=float32))
('is fg', array([0.13358258, 0.86641747], dtype=float32))
(0.35884282, 0.01893594)
-----
[0 1 2 3 4 5 6 7 8 9]
(array([ 0.00613922,  0.0722416 , -0.010372  ,  0.04292551], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8203398300849575
0.8509695290858725
0.8452993768626389
0.7637014596529882
(4, 6)
('is fg', array([0.97374165, 0.02625831], dtype=float32))
('is fg', array([0.9553085 

(array([ 0.08049886, -0.20216827, -0.05794102,  0.09728102], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.7878250591016549
0.6973140495867769
0.7595997207353968
0.5992091183996279
0.7967806841046278
0.7687093275488069
0.7871720116618076
(7, 14)
('is fg', array([0.9244349 , 0.07556514], dtype=float32))
('is fg', array([0.83000696, 0.16999301], dtype=float32))
('is fg', array([0.7972494 , 0.20275062], dtype=float32))
('is fg', array([0.8544462 , 0.14555386], dtype=float32))
('is fg', array([0.8629054 , 0.13709456], dtype=float32))
('is fg', array([0.8741676, 0.1258324], dtype=float32))
('is fg', array([0.14572649, 0.8542735 ], dtype=float32))
(0.34171325, 0.015392268)
-----
[0 1 2 3 4 5 6 7 8 9]
(array([ 0.0085617 ,  0.06070952, -0.01228059,  0.03689649], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8257042253521126
0.8637873754152824
0.8696129563546527
0.776431718061674
(4, 6)
('is fg', array([0.9755662, 0.0244338], dtype=float32))
('is fg', array([0.9610889 , 0.

(array([ 0.00745105,  0.04939943, -0.00081724,  0.03920938], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8257042253521126
0.8683551349846924
0.8945757997218359
0.8307692307692308
(4, 6)
('is fg', array([0.97641015, 0.02358982], dtype=float32))
('is fg', array([0.9644698 , 0.03553024], dtype=float32))
('is fg', array([0.9114022 , 0.08859775], dtype=float32))
('is fg', array([0.97482705, 0.02517292], dtype=float32))
(0.25572416, 0.0043439465)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.01577978, -0.09610502,  0.1633643 ,  0.23639466], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7349036402569593
0.85
0.7206132879045997
0.6816479400749064
0.6787650247466416
0.6946308724832215
(6, 5)
('is fg', array([0.8475775 , 0.15242249], dtype=float32))
('is fg', array([0.8332165 , 0.16678348], dtype=float32))
('is fg', array([0.86676455, 0.13323545], dtype=float32))
('is fg', array([0.80518144, 0.19481856], dtype=float32))
('is fg', array([0.7475329 , 0.25246704], dtyp

(array([ 0.00478067,  0.04275392, -0.00277811,  0.03484664], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8562858633281168
0.8936530324400564
0.8945757997218359
0.8552338530066815
(4, 6)
('is fg', array([0.97690797, 0.02309205], dtype=float32))
('is fg', array([0.9668929 , 0.03310714], dtype=float32))
('is fg', array([0.9221841 , 0.07781594], dtype=float32))
('is fg', array([0.97736585, 0.02263413], dtype=float32))
(0.24123968, 0.0032861636)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.01142795, -0.0850556 ,  0.15090969,  0.2073337 ], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7557483731019523
0.8666666666666667
0.7300295857988166
0.7091369569452561
0.704474754726011
0.7171260732037957
(6, 5)
('is fg', array([0.85369784, 0.14630221], dtype=float32))
('is fg', array([0.8361828 , 0.16381721], dtype=float32))
('is fg', array([0.86939174, 0.13060822], dtype=float32))
('is fg', array([0.8137546 , 0.18624537], dtype=float32))
('is fg', array([0.7575572 , 0.24

(array([ 0.00699057,  0.03884576, -0.00029867,  0.03316194], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8562858633281168
0.9436619718309859
0.9069373942470389
0.8683551349846924
(4, 6)
('is fg', array([0.97738487, 0.02261511], dtype=float32))
('is fg', array([0.9687755 , 0.03122452], dtype=float32))
('is fg', array([0.93056726, 0.06943269], dtype=float32))
('is fg', array([0.97941804, 0.0205819 ], dtype=float32))
(0.22844242, 0.0029696254)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.00993019, -0.07467204,  0.14010349,  0.18429944], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7660510114335972
0.8813559322033898
0.7658937920718025
0.7344632768361582
0.7142857142857143
0.738654875494531
(6, 5)
('is fg', array([0.85910994, 0.14089003], dtype=float32))
('is fg', array([0.839155  , 0.16084501], dtype=float32))
('is fg', array([0.8724859 , 0.12751412], dtype=float32))
('is fg', array([0.8224977 , 0.17750229], dtype=float32))
('is fg', array([0.76549464, 0.23

(array([ 0.00421188,  0.03496599, -0.00061675,  0.0267255 ], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8562858633281168
0.9577464788732394
0.9069373942470389
0.8854601056435919
(4, 6)
('is fg', array([0.9778137 , 0.02218629], dtype=float32))
('is fg', array([0.97009474, 0.02990532], dtype=float32))
('is fg', array([0.93700945, 0.06299053], dtype=float32))
('is fg', array([0.9811298 , 0.01887019], dtype=float32))
(0.21670543, 0.0024843141)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.00733688, -0.06778401,  0.12901302,  0.16393253], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7660510114335972
0.8813559322033898
0.7787072243346007
0.7653490328006728
0.7355473554735548
0.7477031802120141
(6, 5)
('is fg', array([0.86363065, 0.13636929], dtype=float32))
('is fg', array([0.84203273, 0.15796728], dtype=float32))
('is fg', array([0.8755644 , 0.12443567], dtype=float32))
('is fg', array([0.8306773, 0.1693227], dtype=float32))
('is fg', array([0.7710755 , 0.228

(array([ 0.00167372,  0.03405218, -0.00104823,  0.02007796], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8724422003720436
0.9714285714285714
0.9069373942470389
0.9295774647887324
(4, 6)
('is fg', array([0.97808844, 0.02191151], dtype=float32))
('is fg', array([0.9709674 , 0.02903256], dtype=float32))
('is fg', array([0.9419392 , 0.05806085], dtype=float32))
('is fg', array([0.98243654, 0.0175635 ], dtype=float32))
(0.20521134, 0.0020493334)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.0069733 , -0.06120745,  0.11796547,  0.14634317], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7780259044216168
0.8832271762208068
0.8006158583525789
0.7883907299111977
0.7509832841691249
0.7477031802120141
(6, 5)
('is fg', array([0.8675346 , 0.13246547], dtype=float32))
('is fg', array([0.84476656, 0.15523344], dtype=float32))
('is fg', array([0.87845534, 0.12154464], dtype=float32))
('is fg', array([0.83839256, 0.16160747], dtype=float32))
('is fg', array([0.7753936 , 0.2

(array([ 0.01605985,  0.03049534, -0.0109911 , -0.00026838], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.9019230769230769
0.9521586931155193
0.5205593821749113
0.9241540256709452
0.9061784897025171
(5, 5)
('is fg', array([0.9798125 , 0.02018751], dtype=float32))
('is fg', array([0.9733532 , 0.02664685], dtype=float32))
('is fg', array([0.94947016, 0.0505298 ], dtype=float32))
('is fg', array([0.9847921 , 0.01520792], dtype=float32))
('is fg', array([0.20938289, 0.7906171 ], dtype=float32))
(0.33785066, 0.012739258)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.01453568, -0.05754355,  0.10377911,  0.12497104], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.7903811252268602
0.896551724137931
0.8144087705559906
0.7877058177826565
0.76375
0.7863724539282251
(6, 5)
('is fg', array([0.8750351 , 0.12496492], dtype=float32))
('is fg', array([0.8507968 , 0.14920321], dtype=float32))
('is fg', array([0.8841007 , 0.11589934], dtype=float32))
('is fg', array([0.8494634

(array([ 0.0643179 , -0.09808458, -0.01918154,  0.05697407], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.8414959928762245
0.6376008064516129
0.8402625820568927
0.7626858021527422
0.8619060120766605
0.7885714285714286
0.8344788087056129
0.6187450357426529
(8, 13)
('is fg', array([0.9226487 , 0.07735129], dtype=float32))
('is fg', array([0.8522854 , 0.14771459], dtype=float32))
('is fg', array([0.82933587, 0.17066415], dtype=float32))
('is fg', array([0.88577753, 0.11422251], dtype=float32))
('is fg', array([0.9016319 , 0.09836809], dtype=float32))
('is fg', array([0.92719907, 0.07280095], dtype=float32))
('is fg', array([0.60623664, 0.3937634 ], dtype=float32))
('is fg', array([0.4882304, 0.5117696], dtype=float32))
(0.31052533, 0.010972561)
-----
[0 1 2 3 4 5 6 7 8 9]
(array([ 0.00339898,  0.03738943,  0.00545447, -0.00486638], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.8849056603773585
0.98
0.6574585635359116
0.9061784897025171
0.9245283018867925
(5, 5)
('is

(array([ 0.01136125,  0.00354646, -0.00696774, -0.01797171], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.707774798927614
0.9324938789786639
0.9491386382280558
0.8741594620557157
0.8144171779141104
(5, 21)
('is fg', array([0.95644116, 0.04355879], dtype=float32))
('is fg', array([0.65132487, 0.34867516], dtype=float32))
('is fg', array([0.75391006, 0.24608994], dtype=float32))
('is fg', array([0.8547326, 0.1452674], dtype=float32))
('is fg', array([0.76619166, 0.23380837], dtype=float32))
(0.34098107, 0.011690815)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([ 0.04493232, -0.08889688, -0.01095702,  0.06340956], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.8253275109170306
0.6483765416561792
0.8227571115973742
0.80390625
0.8787800465236495
0.8197674418604651
0.8476953907815631
0.5721596724667349
(8, 13)
('is fg', array([0.9224811 , 0.07751881], dtype=float32))
('is fg', array([0.85406625, 0.14593376], dtype=float32))
('is fg', arr

(array([-0.01676794, -0.01723711,  0.09249095, -0.01107144], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9081081081081082
0.9010507880910683
0.7291169451073986
0.5113350125944585
0.7378939277478862
0.7386609071274298
0.8524590163934426
0.529338327091136
0.5301635991820041
(9, 10)
('is fg', array([0.89076626, 0.10923367], dtype=float32))
('is fg', array([0.9339847 , 0.06601528], dtype=float32))
('is fg', array([0.8275669 , 0.17243306], dtype=float32))
('is fg', array([0.9129033 , 0.08709671], dtype=float32))
('is fg', array([0.872885  , 0.12711507], dtype=float32))
('is fg', array([0.86322993, 0.13677008], dtype=float32))
('is fg', array([0.7603902 , 0.23960975], dtype=float32))
('is fg', array([0.784662  , 0.21533798], dtype=float32))
('is fg', array([0.79058105, 0.20941895], dtype=float32))
(0.1799157, 0.020668983)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
(array([ 0.01055766,  0.00129898, -0.01208644, -0.01519409], dtype=float

(array([ 0.09800854,  0.03403831, -0.09322945,  0.02076804], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9196078431372549
0.9050131926121372
0.8045977011494253
0.9057005860415557
0.9523809523809523
(5, 9)
('is fg', array([0.9860567 , 0.01394331], dtype=float32))
('is fg', array([0.9673895 , 0.03261048], dtype=float32))
('is fg', array([0.98780453, 0.01219544], dtype=float32))
('is fg', array([0.88941187, 0.11058819], dtype=float32))
('is fg', array([0.9481278 , 0.05187226], dtype=float32))
(0.20816569, 0.0030093847)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([-0.01177262, -0.01237702,  0.08875021, -0.01542376], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9264705882352942
0.882661996497373
0.7854545454545454
0.5412844036697247
0.7620528771384136
0.728414442700157
0.8681135225375626
0.5535983895319577
0.5962145110410094
(9, 10)
('is fg', array([0.891407  , 0.10859298], dtype=float32))
('is fg', array([0.93590707, 0.06409288], dtype=f

(array([-0.05476987,  0.05519546,  0.02158117, -0.01178247], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.8955223880597015
0.8902471432367791
0.8810779144698301
0.8970588235294118
0.8923943661971832
0.7947855340622372
0.7380191693290735
(7, 13)
('is fg', array([0.9628021 , 0.03719793], dtype=float32))
('is fg', array([0.98543   , 0.01457003], dtype=float32))
('is fg', array([0.9443803 , 0.05561973], dtype=float32))
('is fg', array([0.9712902, 0.0287098], dtype=float32))
('is fg', array([0.9415165 , 0.05848347], dtype=float32))
('is fg', array([0.9565693 , 0.04343069], dtype=float32))
('is fg', array([0.9080219 , 0.09197804], dtype=float32))
(0.076614514, 0.008206988)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
(array([ 0.0850874 ,  0.03552556, -0.08512904,  0.01706233], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9243697478991597
0.8879109500388299
0.822239624119029
0.9057005860415557
0.9523809523809523
(5, 9)
('is fg', array([0.98697567, 0.01302432], dty

(array([-0.02170043,  0.01781099, -0.01749822,  0.01448348], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.8650875386199794
0.8072845882033162
0.7701863354037267
0.7126273394930112
0.8327137546468402
0.8608108108108108
0.9245283018867925
0.6772082878953108
(8, 15)
('is fg', array([0.9644446, 0.0355554], dtype=float32))
('is fg', array([0.981111  , 0.01888901], dtype=float32))
('is fg', array([0.96848655, 0.03151349], dtype=float32))
('is fg', array([0.9597843 , 0.04021564], dtype=float32))
('is fg', array([0.94364756, 0.05635247], dtype=float32))
('is fg', array([0.9437464 , 0.05625354], dtype=float32))
('is fg', array([0.8146467 , 0.18535332], dtype=float32))
('is fg', array([0.94933563, 0.05066431], dtype=float32))
(0.08196145, 0.0076703853)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.0573144 ,  0.05017384,  0.02123574, -0.00464931], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.8955223880597015
0.8778825995807128
0.89458272327

(array([ 0.03171721,  0.01801532, -0.00073673,  0.0073898 ], dtype=float32), array([120.,  66., 183., 153.,   2.]))
0.7285074857231054
0.9729437229437229
0.9732429539778809
(3, 24)
('is fg', array([0.9431639 , 0.05683611], dtype=float32))
('is fg', array([0.8824352 , 0.11756479], dtype=float32))
('is fg', array([0.9072406 , 0.09275934], dtype=float32))
(0.19919267, 0.0036324875)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([-0.00388778,  0.02865105, -0.04644464,  0.00444194], dtype=float32), array([ 85., 119., 136., 188.,   2.]))
0.9175531914893617
0.8818020754239433
0.9039609332609875
0.6367485182049111
0.8292498105582218
0.952647800504343
0.6671102239964516
(7, 9)
('is fg', array([0.93945175, 0.06054829], dtype=float32))
('is fg', array([0.9408538 , 0.05914626], dtype=float32))
('is fg', array([0.9444085 , 0.05559149], dtype=float32))
('is fg', array([0.9630864 , 0.03691359], dtype=float32))
('is fg', array([0.8086585 , 0.19134153], dtype=float32))
('is fg', array([

(array([-0.01832504,  0.00901047,  0.01437574, -0.02006281], dtype=float32), array([122.,  67., 186., 155.,   2.]))
0.9161554192229039
0.9334941419710544
0.9139784946236559
(3, 22)
('is fg', array([0.95591974, 0.04408028], dtype=float32))
('is fg', array([0.9244677 , 0.07553225], dtype=float32))
('is fg', array([0.87495834, 0.1250417 ], dtype=float32))
(0.21659943, 0.0013384403)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(array([0.03924101, 0.03615967, 0.01854642, 0.01383705], dtype=float32), array([ 85., 118., 135., 189.,   2.]))
0.8578088578088578
0.8719298245614036
0.8536905700026267
0.6802565277141548
0.9403546480386888
0.7285605868960283
0.8367662203913491
0.8670645686380901
(8, 4)
('is fg', array([0.9300972 , 0.06990285], dtype=float32))
('is fg', array([0.9627516 , 0.03724835], dtype=float32))
('is fg', array([0.96702707, 0.03297293], dtype=float32))
('is fg', array([0.9521387 , 0.04786126], dtype=float32))
('is fg', array([0.74411595, 0.25588405], dtype=float32))
('is fg', arr

(array([ 0.0107836 , -0.00350324,  0.0341204 , -0.02173409], dtype=float32), array([122.,  66., 187., 155.,   2.]))
0.8753937696884844
0.8129462160875773
0.9521892299949672
0.96318407960199
(4, 23)
('is fg', array([0.9450306 , 0.05496935], dtype=float32))
('is fg', array([0.9291147 , 0.07088532], dtype=float32))
('is fg', array([0.88793314, 0.11206685], dtype=float32))
('is fg', array([0.7312827, 0.2687173], dtype=float32))
(0.23017555, 0.002834625)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
(array([ 0.00057151,  0.00730285, -0.01616884, -0.00704229], dtype=float32), array([122.,  66., 186., 156.,   2.]))
0.9736065289112693
0.9622542134831461
(2, 33)
('is fg', array([0.967816  , 0.03218396], dtype=float32))
('is fg', array([0.88475865, 0.11524136], dtype=float32))
(0.13705948, 0.0005073483)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
(array([ 0.00561891,  0.0073755 , 

(array([-0.00017148,  0.01900548, -0.01707536, -0.00695823], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.9196078431372549
0.9855072463768116
0.7483870967741936
0.913548012764723
1.0
(5, 5)
('is fg', array([0.9866648 , 0.01333524], dtype=float32))
('is fg', array([0.9803427 , 0.01965728], dtype=float32))
('is fg', array([0.96573323, 0.03426678], dtype=float32))
('is fg', array([0.991861  , 0.00813903], dtype=float32))
('is fg', array([0.9697407 , 0.03025934], dtype=float32))
(0.11797296, 0.003247289)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([ 0.00395108, -0.00671014,  0.05348535,  0.04330721], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.8299190090519295
0.9398435392500675
0.8825268817204301
0.9109109109109109
0.8703605514316013
0.8476215368531103
(6, 5)
('is fg', array([0.9023042 , 0.09769586], dtype=float32))
('is fg', array([0.87597114, 0.12402883], dtype=float32))
('is fg', array([0.9145374 , 0.08546262], dtype=float32))
('is fg', array([0.8959845 , 0

(array([ 0.00066646, -0.04686674, -0.02114151,  0.06246957], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9115853658536586
0.7504736129905277
0.8969422423556059
0.8427773343974462
0.8952431854623196
0.6165413533834586
0.8840287769784173
0.8121516164994426
0.6951026856240127
(9, 12)
('is fg', array([0.94204044, 0.05795963], dtype=float32))
('is fg', array([0.8716698 , 0.12833013], dtype=float32))
('is fg', array([0.8502287 , 0.14977129], dtype=float32))
('is fg', array([0.90779483, 0.09220514], dtype=float32))
('is fg', array([0.9261096 , 0.07389043], dtype=float32))
('is fg', array([0.94569004, 0.05431001], dtype=float32))
('is fg', array([0.89600724, 0.10399279], dtype=float32))
('is fg', array([0.90109736, 0.09890264], dtype=float32))
('is fg', array([0.49565613, 0.50434387], dtype=float32))
(0.2655819, 0.007886891)
-----
[0 1 2 3 4 5 6 7 8 9]
(array([ 0.00215449,  0.01759986, -0.01653631, -0.007292  ], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.919607843137

(array([ 0.00392144,  0.01158731, -0.00870029, -0.02246842], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.8317028685126845
0.9886363636363636
0.9345365053322395
0.9209638554216868
0.8785405664906385
(5, 21)
('is fg', array([0.96785283, 0.03214717], dtype=float32))
('is fg', array([0.85578495, 0.14421497], dtype=float32))
('is fg', array([0.78984797, 0.21015203], dtype=float32))
('is fg', array([0.8817279 , 0.11827218], dtype=float32))
('is fg', array([0.80906475, 0.19093531], dtype=float32))
(0.2151157, 0.0027373903)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([-0.00165048, -0.04353616, -0.01978666,  0.06220849], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9115853658536586
0.7605595172792101
0.8969422423556059
0.8427773343974462
0.9081196581196581
0.6409725814795655
0.8840287769784173
0.8121516164994426
0.7149706979222163
(9, 12)
('is fg', array([0.9440831 , 0.05591686], dtype=float32))
('is fg', array([0.8737197, 0.1262803], d

(array([-0.0171238 , -0.01349203,  0.06668249, -0.00523077], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9360146252285192
0.882661996497373
0.7805579522576934
0.6587473002159827
0.7724645296899633
0.8880597014925373
0.8843537414965986
0.6896551724137931
0.6921866806502359
(9, 10)
('is fg', array([0.9073551 , 0.09264488], dtype=float32))
('is fg', array([0.95436037, 0.04563965], dtype=float32))
('is fg', array([0.8677842, 0.1322158], dtype=float32))
('is fg', array([0.9338246 , 0.06617536], dtype=float32))
('is fg', array([0.8971452 , 0.10285481], dtype=float32))
('is fg', array([0.8862733 , 0.11372664], dtype=float32))
('is fg', array([0.87031776, 0.12968224], dtype=float32))
('is fg', array([0.9221781 , 0.07782187], dtype=float32))
('is fg', array([0.8953415 , 0.10465851], dtype=float32))
(0.11076231, 0.008608297)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
(array([ 0.00478444,  0.01171689, -0.00876197, -0.02369233], dtype=float3

(array([-0.04893446,  0.03875198,  0.01980651, -0.01443086], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.8929551692589204
0.8947649572649573
0.9467213114754098
0.8840579710144928
0.8748964374482188
0.8513591671486408
0.7960199004975125
(7, 13)
('is fg', array([0.97082496, 0.02917504], dtype=float32))
('is fg', array([0.98955613, 0.01044387], dtype=float32))
('is fg', array([0.95969546, 0.04030457], dtype=float32))
('is fg', array([0.98015046, 0.01984948], dtype=float32))
('is fg', array([0.97988933, 0.02011066], dtype=float32))
('is fg', array([0.9632179 , 0.03678213], dtype=float32))
('is fg', array([0.9761355 , 0.02386449], dtype=float32))
(0.051240277, 0.003421751)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
(array([ 0.06243744,  0.0255704 , -0.06498337,  0.01124353], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9470588235294117
0.9353287012292891
0.8853606027987083
0.9400544959128065
0.9663865546218487
(5, 9)
('is fg', array([0.9925746 , 0.00742544], 

(array([-0.016416  ,  0.01525762, -0.01847534,  0.01570485], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.8933794203669236
0.8540748898678414
0.8497925311203319
0.8089219330855019
0.8593350383631714
0.873581847649919
0.9245283018867925
0.8490708186840783
(8, 15)
('is fg', array([0.9740537 , 0.02594625], dtype=float32))
('is fg', array([0.98604465, 0.01395537], dtype=float32))
('is fg', array([0.9799344 , 0.02006556], dtype=float32))
('is fg', array([0.9728697 , 0.02713029], dtype=float32))
('is fg', array([0.9774368 , 0.02256315], dtype=float32))
('is fg', array([0.9818694 , 0.01813058], dtype=float32))
('is fg', array([0.8352443 , 0.16475573], dtype=float32))
('is fg', array([0.95208246, 0.04791755], dtype=float32))
(0.052338943, 0.0031208394)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.04522284,  0.03846557,  0.01715976, -0.01441815], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.8929551692589204
0.9073672806067172
0.915369374

-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
(array([0.02187311, 0.01756795, 0.00175913, 0.01043437], dtype=float32), array([120.,  66., 183., 153.,   2.]))
0.8783669320684397
0.9886363636363636
0.9887640449438202
(3, 24)
('is fg', array([0.9562386 , 0.04376137], dtype=float32))
('is fg', array([0.93387836, 0.0661217 ], dtype=float32))
('is fg', array([0.92777526, 0.07222475], dtype=float32))
(0.13817193, 0.0005106071)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([-0.00742331,  0.01501713, -0.03382605, -0.00677135], dtype=float32), array([ 85., 119., 136., 188.,   2.]))
0.9667582417582418
0.8942842690945878
0.9286510590858417
0.8876523582405935
0.897736143637783
0.9291014014839242
0.7790262172284644
(7, 9)
('is fg', array([0.95646584, 0.0435342 ], dtype=float32))
('is fg', array([0.9519044 , 0.04809558], dtype=float32))
('is fg', array([0.95742625, 0.04257373], dtype=float32))
('is fg', array([0.9752965 , 0.02470345], dtype

(array([-0.0144185 ,  0.00983147,  0.01640192, -0.00915394], dtype=float32), array([122.,  67., 186., 155.,   2.]))
0.9513816019587268
0.9440234240440923
0.9340659340659341
(3, 22)
('is fg', array([0.9657367 , 0.03426337], dtype=float32))
('is fg', array([0.9564526 , 0.04354736], dtype=float32))
('is fg', array([0.90043354, 0.09956651], dtype=float32))
(0.15316151, 0.00070863095)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(array([0.0379077 , 0.02834451, 0.01717118, 0.01588032], dtype=float32), array([ 85., 118., 135., 189.,   2.]))
0.8857741681949175
0.9180243082492888
0.8966150616636054
0.7849355797819624
0.9667755991285403
0.8041237113402062
0.8933333333333333
0.9230769230769231
(8, 4)
('is fg', array([0.9438231 , 0.05617693], dtype=float32))
('is fg', array([0.97386926, 0.02613075], dtype=float32))
('is fg', array([0.97669196, 0.02330801], dtype=float32))
('is fg', array([0.96760374, 0.03239625], dtype=float32))
('is fg', array([0.78841686, 0.21158314], dtype=float32))
('is fg', ar

(array([ 0.01055784, -0.00275908,  0.02571892, -0.01334956], dtype=float32), array([122.,  66., 187., 155.,   2.]))
0.9772727272727273
0.8687767886580943
0.9630996309963099
0.9523967490462764
(4, 23)
('is fg', array([0.9566772 , 0.04332273], dtype=float32))
('is fg', array([0.95184046, 0.04815952], dtype=float32))
('is fg', array([0.9110259 , 0.08897405], dtype=float32))
('is fg', array([0.7773379 , 0.22266203], dtype=float32))
(0.17029274, 0.0011147826)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
(array([ 0.0031225 ,  0.01075668, -0.01357599, -0.01572945], dtype=float32), array([122.,  66., 186., 156.,   2.]))
0.984375
0.9777777777777777
(2, 33)
('is fg', array([0.97607124, 0.02392881], dtype=float32))
('is fg', array([0.9114374 , 0.08856261], dtype=float32))
(0.09946462, 0.00015417406)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
(array([ 0.00600596,  0.00448142,  0.0

(array([ 0.00761977,  0.01548487, -0.01131631, -0.00484756], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.9329354930377949
0.9381563593932322
0.8499156829679595
0.9461606354810238
1.0
(5, 5)
('is fg', array([0.990418  , 0.00958202], dtype=float32))
('is fg', array([0.98631346, 0.0136865 ], dtype=float32))
('is fg', array([0.9746987 , 0.02530132], dtype=float32))
('is fg', array([0.9948874 , 0.00511265], dtype=float32))
('is fg', array([0.9837673 , 0.01623273], dtype=float32))
(0.08385876, 0.0008533405)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([0.00431802, 0.01009394, 0.04918926, 0.02276682], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.8299190090519295
0.9398435392500675
0.5699734278122232
0.8949771689497716
0.9362139917695473
0.9478672985781991
0.8990825688073395
(7, 4)
('is fg', array([0.9253329, 0.0746671], dtype=float32))
('is fg', array([0.8935238 , 0.10647618], dtype=float32))
('is fg', array([0.933658  , 0.06634203], dtype=float32))
('is fg', array

(array([ 0.00604076,  0.01362901, -0.00771937, -0.0269025 ], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.8799730276466622
0.9735967826543102
0.9491386382280558
0.9305307579938322
0.9024312220089571
(5, 21)
('is fg', array([0.97463566, 0.02536433], dtype=float32))
('is fg', array([0.8926653 , 0.10733473], dtype=float32))
('is fg', array([0.816919  , 0.18308097], dtype=float32))
('is fg', array([0.896381  , 0.10361901], dtype=float32))
('is fg', array([0.83705133, 0.16294865], dtype=float32))
(0.16875127, 0.0013873104)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([-0.01114557, -0.02784274, -0.01223949,  0.05711662], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9591836734693877
0.8221967307140808
0.9289756649688738
0.5024483713008303
0.8612747723620782
0.9389671361502347
0.7228404875463699
0.9104172745841844
0.8421052631578947
0.8164170826400444
(10, 11)
('is fg', array([0.95695955, 0.04304041], dtype=float32))
('is fg', array([0.8

(array([ 0.04490059,  0.01737175, -0.0500844 ,  0.00595881], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9663865546218487
0.9669555796316359
0.9157808667211774
0.9271701155603332
0.9803921568627451
(5, 9)
('is fg', array([0.99507385, 0.00492617], dtype=float32))
('is fg', array([0.98104113, 0.01895884], dtype=float32))
('is fg', array([0.9945856 , 0.00541449], dtype=float32))
('is fg', array([0.9348895 , 0.06511047], dtype=float32))
('is fg', array([0.9746425 , 0.02535743], dtype=float32))
(0.10732458, 0.00054458587)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([-0.0101655 , -0.01206707,  0.04683892, -0.00532271], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9360146252285192
0.8961493582263711
0.7758620689655172
0.7186978297161937
0.7955815810487091
0.9037974683544304
0.9142857142857143
0.7738693467336684
0.7252747252747253
(9, 10)
('is fg', array([0.92121935, 0.07878067], dtype=float32))
('is fg', array([0.9655425 , 0.03445754], dtyp

(array([-0.00832016,  0.01031619, -0.01739206,  0.02097517], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.8933794203669236
0.8665382498624106
0.906390134529148
0.8320783132530121
0.8879109500388299
0.8914100486223663
0.948509485094851
0.9143158449775903
(8, 15)
('is fg', array([0.9799051 , 0.02009486], dtype=float32))
('is fg', array([0.98905677, 0.01094325], dtype=float32))
('is fg', array([0.98570824, 0.01429178], dtype=float32))
('is fg', array([0.97966844, 0.02033158], dtype=float32))
('is fg', array([0.9855583 , 0.01444171], dtype=float32))
('is fg', array([0.98944503, 0.01055495], dtype=float32))
('is fg', array([0.8510827 , 0.14891729], dtype=float32))
('is fg', array([0.95478505, 0.04521497], dtype=float32))
(0.041185323, 0.0018540054)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.03384324,  0.03027555,  0.00995174, -0.01072947], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.9073170731707317
0.9203296703296703
0.8742953776

(array([0.01829834, 0.01819402, 0.00356666, 0.01495405], dtype=float32), array([120.,  66., 183., 153.,   2.]))
0.9117135905457073
0.9887640449438202
0.9887640449438202
(3, 24)
('is fg', array([0.964031  , 0.03596898], dtype=float32))
('is fg', array([0.95381093, 0.046189  ], dtype=float32))
('is fg', array([0.9392968 , 0.06070316], dtype=float32))
(0.11093031, 0.00026945747)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([-0.00989998,  0.00582827, -0.02703919, -0.00206875], dtype=float32), array([ 85., 119., 136., 188.,   2.]))
0.9667582417582418
0.9068992049243396
0.9423076923076923
0.9530090684253916
0.9227524387028737
0.9473241804427011
0.7655068078668684
(7, 9)
('is fg', array([0.9657675 , 0.03423255], dtype=float32))
('is fg', array([0.9590948, 0.0409051], dtype=float32))
('is fg', array([0.9651279 , 0.03487206], dtype=float32))
('is fg', array([0.9813416 , 0.01865837], dtype=float32))
('is fg', array([0.9607401 , 0.03925993], dtype=float32))
('is fg', array([0.95

(array([-0.01166155,  0.00907668,  0.01321039, -0.00672705], dtype=float32), array([122.,  67., 186., 155.,   2.]))
0.9624060150375939
0.9440234240440923
0.9555555555555556
(3, 22)
('is fg', array([0.97198683, 0.02801311], dtype=float32))
('is fg', array([0.9699702 , 0.03002976], dtype=float32))
('is fg', array([0.916314  , 0.08368602], dtype=float32))
(0.12385193, 0.00038980632)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(array([0.03313323, 0.02991558, 0.02121552, 0.01054723], dtype=float32), array([ 85., 118., 135., 189.,   2.]))
0.9148766905330151
0.948437082554101
0.9223404255319149
0.8517382413087935
0.9667755991285403
0.9083969465648855
0.9357798165137615
0.9230769230769231
(8, 4)
('is fg', array([0.9506526 , 0.04934737], dtype=float32))
('is fg', array([0.9794257 , 0.02057427], dtype=float32))
('is fg', array([0.98188215, 0.01811779], dtype=float32))
('is fg', array([0.97550464, 0.02449536], dtype=float32))
('is fg', array([0.812357  , 0.18764299], dtype=float32))
('is fg', arr

(array([ 0.0101424 , -0.0027246 ,  0.02228703, -0.01134298], dtype=float32), array([122.,  66., 187., 155.,   2.]))
0.9735967826543102
0.9077751598788287
0.9630996309963099
0.9523967490462764
(4, 23)
('is fg', array([0.96399176, 0.03600831], dtype=float32))
('is fg', array([0.96369064, 0.03630933], dtype=float32))
('is fg', array([0.925653  , 0.07434703], dtype=float32))
('is fg', array([0.81042063, 0.1895794 ], dtype=float32))
(0.13944781, 0.0006350405)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
(array([ 0.0020801 ,  0.00618393, -0.01302584, -0.01462705], dtype=float32), array([122.,  66., 186., 156.,   2.]))
0.973314606741573
0.9777777777777777
(2, 33)
('is fg', array([0.98057175, 0.01942826], dtype=float32))
('is fg', array([0.9282507 , 0.07174928], dtype=float32))
(0.081189044, 0.00011807437)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
(array([ 0.00632802,  0.0044

(array([ 0.01315596,  0.01152903, -0.00699743, -0.00034097], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.927603115085088
0.9196454103517301
0.8792215226101889
0.96
1.0
(5, 5)
('is fg', array([0.99206686, 0.00793317], dtype=float32))
('is fg', array([0.98887503, 0.01112497], dtype=float32))
('is fg', array([0.9792571 , 0.02074289], dtype=float32))
('is fg', array([0.9962213 , 0.00377868], dtype=float32))
('is fg', array([0.99178773, 0.00821225], dtype=float32))
(0.067028545, 0.0004992514)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([0.00561718, 0.00944318, 0.0366336 , 0.01641888], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.8707214971681851
0.9398435392500675
0.6784604350944299
0.8949771689497716
0.9673133138453361
0.9478672985781991
0.8990825688073395
(7, 4)
('is fg', array([0.937386  , 0.06261408], dtype=float32))
('is fg', array([0.9037198, 0.0962802], dtype=float32))
('is fg', array([0.943463  , 0.05653694], dtype=float32))
('is fg', array([0.9344526, 0

(array([ 0.00502748,  0.01642555, -0.00570075, -0.02683417], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.9031654186521443
0.9626556016597511
0.9491386382280558
0.9552238805970149
0.9168399168399168
(5, 21)
('is fg', array([0.9787693, 0.0212307], dtype=float32))
('is fg', array([0.9180726 , 0.08192745], dtype=float32))
('is fg', array([0.83941984, 0.16058011], dtype=float32))
('is fg', array([0.9079423 , 0.09205763], dtype=float32))
('is fg', array([0.85952276, 0.14047723], dtype=float32))
(0.1396267, 0.000873116)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([-0.01399922, -0.01904632, -0.0078418 ,  0.05524445], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9795918367346939
0.8897235576923077
0.946928179982694
0.6011080332409973
0.8612747723620782
0.9209508015478165
0.7849550286181521
0.9420289855072463
0.8552338530066815
0.8287139689578714
(10, 11)
('is fg', array([0.96273535, 0.03726462], dtype=float32))
('is fg', array([0.895303

(array([ 0.03847129,  0.01508739, -0.04210337,  0.00307566], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9803921568627451
0.9722222222222222
0.9471928849360756
0.9452054794520548
0.9480626545754328
(5, 9)
('is fg', array([0.99643123, 0.00356872], dtype=float32))
('is fg', array([0.98392975, 0.01607032], dtype=float32))
('is fg', array([0.9958806, 0.0041194], dtype=float32))
('is fg', array([0.94697034, 0.05302966], dtype=float32))
('is fg', array([0.9804418 , 0.01955825], dtype=float32))
(0.086919524, 0.00036529367)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([-0.00603762, -0.00873344,  0.03574758, -0.00725658], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9360146252285192
0.5655229433650268
0.8961493582263711
0.7653061224489796
0.7493627867459643
0.7955815810487091
0.9202142655765435
0.9142857142857143
0.8354143019296254
0.755591054313099
(10, 9)
('is fg', array([0.9277183 , 0.07228167], dtype=float32))
('is fg', array([0.97048193, 

(array([-0.00401744,  0.00635001, -0.01581028,  0.02613651], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.9292874559739908
0.8828146902158677
0.9002557544757033
0.8585858585858586
0.8879109500388299
0.9210888094583448
0.948509485094851
0.9267771245323356
(8, 15)
('is fg', array([0.9837023 , 0.01629765], dtype=float32))
('is fg', array([0.9908731 , 0.00912689], dtype=float32))
('is fg', array([0.98936266, 0.01063741], dtype=float32))
('is fg', array([0.9837294 , 0.01627062], dtype=float32))
('is fg', array([0.9916794 , 0.00832056], dtype=float32))
('is fg', array([0.9941034 , 0.00589659], dtype=float32))
('is fg', array([0.87394154, 0.1260585 ], dtype=float32))
('is fg', array([0.9594031 , 0.04059687], dtype=float32))
(0.032665808, 0.0013171559)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.02817585,  0.02196862,  0.00983726, -0.00844529], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.9073170731707317
0.9202453987730062
0.886792452

(array([0.01719917, 0.01767897, 0.00311654, 0.01606292], dtype=float32), array([120.,  66., 183., 153.,   2.]))
0.9216444132115249
0.973314606741573
0.9887640449438202
(3, 24)
('is fg', array([0.9694901 , 0.03050992], dtype=float32))
('is fg', array([0.96468985, 0.03531016], dtype=float32))
('is fg', array([0.94836545, 0.05163461], dtype=float32))
(0.09281162, 0.00018223887)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([-0.00700673,  0.00474393, -0.01481303,  0.00532736], dtype=float32), array([ 85., 119., 136., 188.,   2.]))
0.9667582417582418
0.9232375979112272
0.9615384615384616
0.9807692307692307
0.953780390061448
0.9663865546218487
0.8397267472411981
(7, 9)
('is fg', array([0.9734946, 0.0265054], dtype=float32))
('is fg', array([0.96508646, 0.03491349], dtype=float32))
('is fg', array([0.9699109 , 0.03008907], dtype=float32))
('is fg', array([0.98515934, 0.01484067], dtype=float32))
('is fg', array([0.9753949 , 0.02460502], dtype=float32))
('is fg', array([0.9731

(array([0.00833344, 0.00486242, 0.00504578, 0.00033103], dtype=float32), array([120.,  66., 186., 159.,   2.]))
0.9745951095585901
0.9789473684210527
(2, 26)
('is fg', array([0.94082546, 0.05917455], dtype=float32))
('is fg', array([0.89049345, 0.1095065 ], dtype=float32))
(0.13514224, 0.0001408894)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(array([-0.01044499,  0.00952377,  0.0107909 , -0.00485503], dtype=float32), array([122.,  67., 186., 155.,   2.]))
0.9588850174216028
0.9440234240440923
0.9411764705882353
(3, 22)
('is fg', array([0.9763332 , 0.02366682], dtype=float32))
('is fg', array([0.97698647, 0.0230135 ], dtype=float32))
('is fg', array([0.92842215, 0.07157787], dtype=float32))
(0.10364327, 0.00023020194)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(array([ 0.03094383,  0.02433166,  0.02018311, -0.00208658], dtype=float32), array([ 85., 118., 135., 189.,   2.]))
0.9148766905330151
0.8920844327176781
0.9356554107950014
0.8691206543967

(array([ 0.01034413, -0.00229295,  0.0210388 , -0.01158745], dtype=float32), array([122.,  66., 187., 155.,   2.]))
0.9735967826543102
0.9271227225850808
0.9630996309963099
0.9630996309963099
(4, 23)
('is fg', array([0.9690002 , 0.03099974], dtype=float32))
('is fg', array([0.9701084 , 0.02989153], dtype=float32))
('is fg', array([0.93664944, 0.06335062], dtype=float32))
('is fg', array([0.8360861 , 0.16391395], dtype=float32))
(0.11731725, 0.0003527306)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
(array([ 0.00045122,  0.00477313, -0.00974665, -0.01509609], dtype=float32), array([122.,  66., 186., 156.,   2.]))
0.973314606741573
0.9777777777777777
(2, 33)
('is fg', array([0.9834907 , 0.01650938], dtype=float32))
('is fg', array([0.93915105, 0.06084901], dtype=float32))
(0.068891816, 6.4081796e-05)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
(array([0.0081904 , 0.004675

(array([ 0.01243025,  0.01199535, -0.00379455,  0.00324126], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.927603115085088
0.9463612641345317
0.9107806691449815
0.96
0.9795918367346939
(5, 5)
('is fg', array([0.99307454, 0.00692541], dtype=float32))
('is fg', array([0.9908953 , 0.00910478], dtype=float32))
('is fg', array([0.9822368 , 0.01776321], dtype=float32))
('is fg', array([0.9969734 , 0.00302658], dtype=float32))
('is fg', array([0.9945147 , 0.00548533], dtype=float32))
(0.058409516, 0.00030016212)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([0.00484324, 0.01367843, 0.02935065, 0.0115437 ], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.8826759860209685
0.9398435392500675
0.7435265104808878
0.9116279069767442
0.9673133138453361
0.9478672985781991
0.9345794392523364
(7, 4)
('is fg', array([0.94861585, 0.05138421], dtype=float32))
('is fg', array([0.91149837, 0.08850158], dtype=float32))
('is fg', array([0.9503718 , 0.04962818], dtype=float32))
('is fg', a

(array([ 0.00637565,  0.0170979 , -0.00517469, -0.02504436], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.8893916540975364
0.937046004842615
0.9491386382280558
0.9552238805970149
0.9168399168399168
(5, 21)
('is fg', array([0.98174334, 0.01825661], dtype=float32))
('is fg', array([0.9314109 , 0.06858908], dtype=float32))
('is fg', array([0.8567441 , 0.14325587], dtype=float32))
('is fg', array([0.9167567 , 0.08324325], dtype=float32))
('is fg', array([0.87641996, 0.12358002], dtype=float32))
(0.11901708, 0.0006005681)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([-0.01459765, -0.01865905, -0.00620349,  0.04945848], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9591836734693877
0.930117501546073
0.9334660221779926
0.6767578125
0.8729641693811075
0.9338565022421524
0.8246001103143961
0.9558823529411765
0.8683551349846924
0.8872997711670481
(10, 11)
('is fg', array([0.9665365 , 0.03346355], dtype=float32))
('is fg', array([0.89935476,

(array([ 0.03620847,  0.01410663, -0.03468477,  0.00245567], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9803921568627451
0.9859154929577465
0.9666574048346763
0.9452054794520548
0.9480626545754328
(5, 9)
('is fg', array([0.99724376, 0.0027563 ], dtype=float32))
('is fg', array([0.9859222 , 0.01407776], dtype=float32))
('is fg', array([0.99672145, 0.00327852], dtype=float32))
('is fg', array([0.9572803 , 0.04271965], dtype=float32))
('is fg', array([0.9844965 , 0.01550355], dtype=float32))
(0.07134342, 0.00027774373)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([-0.00100671, -0.00664901,  0.02603491, -0.00824219], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9178368688377652
0.7001434720229556
0.9322235434007135
0.7774001699235344
0.7811418685121108
0.8067476383265857
0.9066666666666666
0.9323131253678635
0.8763188745603752
0.7825383993532741
(10, 9)
('is fg', array([0.93175316, 0.06824685], dtype=float32))
('is fg', array([0.9736372 

(array([ 0.00111168,  0.00552554, -0.01354652,  0.02771175], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.9292874559739908
0.9147982062780269
0.8968209704406024
0.8834645669291339
0.8874015748031496
0.9210888094583448
0.948509485094851
0.9267771245323356
(8, 15)
('is fg', array([0.986153  , 0.01384702], dtype=float32))
('is fg', array([0.9921061 , 0.00789399], dtype=float32))
('is fg', array([0.9916944 , 0.00830559], dtype=float32))
('is fg', array([0.9863593 , 0.01364074], dtype=float32))
('is fg', array([0.99407804, 0.00592195], dtype=float32))
('is fg', array([0.99593997, 0.00406   ], dtype=float32))
('is fg', array([0.892729, 0.107271], dtype=float32))
('is fg', array([0.9629288 , 0.03707118], dtype=float32))
(0.026841797, 0.0008989495)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.02211379,  0.01952467,  0.01222053, -0.00723604], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.9216702224931423
0.9518315546582059
0.8928974069898

(array([0.01543918, 0.01553742, 0.00270679, 0.01471695], dtype=float32), array([120.,  66., 183., 153.,   2.]))
0.962183374955405
0.984375
0.9887640449438202
(3, 24)
('is fg', array([0.9735603 , 0.02643973], dtype=float32))
('is fg', array([0.9712658 , 0.02873419], dtype=float32))
('is fg', array([0.9549711 , 0.04502894], dtype=float32))
(0.07912835, 0.000117287105)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(array([-0.00979228,  0.00490276, -0.00017432,  0.00687543], dtype=float32), array([ 85., 119., 136., 188.,   2.]))
0.9667582417582418
0.949708840656432
0.9433962264150944
0.9665551839464883
0.9722222222222222
0.9663865546218487
0.8799149840595112
(7, 9)
('is fg', array([0.9786638 , 0.02133617], dtype=float32))
('is fg', array([0.9690581 , 0.03094187], dtype=float32))
('is fg', array([0.9734408 , 0.02655913], dtype=float32))
('is fg', array([0.9877543 , 0.01224577], dtype=float32))
('is fg', array([0.9819079 , 0.01809209], dtype=float32))
('is fg', array([0.9806927 , 0

(array([0.0085196 , 0.00411533, 0.00733845, 0.00098352], dtype=float32), array([120.,  66., 186., 159.,   2.]))
0.9745951095585901
0.9789473684210527
(2, 26)
('is fg', array([0.94894326, 0.05105678], dtype=float32))
('is fg', array([0.90642977, 0.09357021], dtype=float32))
(0.11833375, 0.00010115259)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(array([-0.00773043,  0.01045426,  0.00769792, -0.00372501], dtype=float32), array([122.,  67., 186., 155.,   2.]))
0.9846153846153847
0.9583843329253366
0.9517551443887255
(3, 22)
('is fg', array([0.9797661 , 0.02023399], dtype=float32))
('is fg', array([0.98132277, 0.01867727], dtype=float32))
('is fg', array([0.9373137 , 0.06268631], dtype=float32))
(0.08806934, 0.00014396236)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(array([ 0.02841803,  0.02247017,  0.02458871, -0.0054759 ], dtype=float32), array([ 85., 118., 135., 189.,   2.]))
0.9406073636119323
0.8920844327176781
0.94896331738437
0.88449531737773

(array([ 0.01154715, -0.00271172,  0.01881251, -0.01245819], dtype=float32), array([122.,  66., 187., 155.,   2.]))
0.9846153846153847
0.9371091035441279
0.9775280898876404
0.9630996309963099
(4, 23)
('is fg', array([0.9730566 , 0.02694339], dtype=float32))
('is fg', array([0.9746436 , 0.02535645], dtype=float32))
('is fg', array([0.94452816, 0.05547182], dtype=float32))
('is fg', array([0.85757947, 0.14242058], dtype=float32))
(0.100087605, 0.00024770026)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
(array([-0.00059707,  0.00425393, -0.00836053, -0.01352861], dtype=float32), array([122.,  66., 186., 156.,   2.]))
0.9626671297100191
0.9777777777777777
(2, 33)
('is fg', array([0.985768  , 0.01423193], dtype=float32))
('is fg', array([0.94732505, 0.05267499], dtype=float32))
(0.059224054, 4.7715417e-05)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
(array([0.00844212, 0.004

(array([ 0.01139078,  0.01090258, -0.00209442,  0.00265707], dtype=float32), array([ 88.,  35., 137., 103.,   2.]))
0.9323131253678635
0.9463612641345317
0.9518701072774717
0.96
0.9795918367346939
(5, 5)
('is fg', array([0.9938397 , 0.00616033], dtype=float32))
('is fg', array([0.9922891 , 0.00771089], dtype=float32))
('is fg', array([0.98458374, 0.01541625], dtype=float32))
('is fg', array([0.9975096 , 0.00249035], dtype=float32))
('is fg', array([0.99600875, 0.00399126], dtype=float32))
(0.050432086, 0.00016943029)
-----
[ 0  1  2  3  4  5  6  7  8  9 10]
(array([0.00201683, 0.01650952, 0.02502752, 0.00922519], dtype=float32), array([ 87., 118., 138., 188.,   2.]))
0.8983739837398373
0.95361380798274
0.7866258295048494
0.9302325581395349
0.94896331738437
0.9478672985781991
0.9345794392523364
(7, 4)
('is fg', array([0.956672  , 0.04332799], dtype=float32))
('is fg', array([0.91840756, 0.08159249], dtype=float32))
('is fg', array([0.955988  , 0.04401203], dtype=float32))
('is fg', arra

(array([ 0.00756636,  0.01757484, -0.00410336, -0.02398516], dtype=float32), array([120.,  65., 186., 156.,   2.]))
0.9129993229519295
0.937046004842615
0.9491386382280558
0.9701492537313433
0.9305307579938322
(5, 21)
('is fg', array([0.98417735, 0.01582266], dtype=float32))
('is fg', array([0.9410901 , 0.05890986], dtype=float32))
('is fg', array([0.87169266, 0.12830736], dtype=float32))
('is fg', array([0.92402464, 0.0759754 ], dtype=float32))
('is fg', array([0.89053535, 0.10946466], dtype=float32))
(0.102815755, 0.00043941793)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([-0.0145053 , -0.01685737, -0.00313266,  0.04329148], dtype=float32), array([ 88.,  36., 138., 104.,   2.]))
0.9795918367346939
0.930117501546073
0.9334660221779926
0.7315214630429261
0.8729641693811075
0.9209508015478165
0.8642186165670367
0.9558823529411765
0.8936530324400564
0.9004861309694023
(10, 11)
('is fg', array([0.9697789 , 0.03022103], dtype=float32))
('is fg', array([0.9

(array([ 0.03199921,  0.01218974, -0.03009883,  0.00360645], dtype=float32), array([ 87.,  35., 138., 106.,   2.]))
0.9803921568627451
0.9859154929577465
0.98
0.9400544959128065
0.9480626545754328
(5, 9)
('is fg', array([0.9978193 , 0.00218067], dtype=float32))
('is fg', array([0.9875916 , 0.01240837], dtype=float32))
('is fg', array([0.99737346, 0.00262656], dtype=float32))
('is fg', array([0.9641449 , 0.03585517], dtype=float32))
('is fg', array([0.9872804 , 0.01271953], dtype=float32))
(0.059778377, 0.00017869283)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(array([ 0.0016123 , -0.00338649,  0.01935818, -0.00906629], dtype=float32), array([150.,  37., 199., 104.,   2.]))
0.9178368688377652
0.8012519561815337
0.9322235434007135
0.7944507361268404
0.7993079584775087
0.850246845858475
0.9066666666666666
0.946236559139785
0.8951069440375037
0.8148148148148148
(10, 9)
('is fg', array([0.93581516, 0.06418476], dtype=float32))
('is fg', array([0.97631466, 0.02368532], 

(array([ 0.00577258,  0.00258679, -0.0123645 ,  0.02553017], dtype=float32), array([149., 118., 200., 187.,   2.]))
0.9292874559739908
0.8976897689768977
0.902915291529153
0.9124423963133641
0.9042524739235089
0.9345794392523364
0.948509485094851
0.9395827688973178
(8, 15)
('is fg', array([0.9879693, 0.0120307], dtype=float32))
('is fg', array([0.9931566 , 0.00684341], dtype=float32))
('is fg', array([0.99326986, 0.00673014], dtype=float32))
('is fg', array([0.98835164, 0.01164833], dtype=float32))
('is fg', array([0.995484  , 0.00451603], dtype=float32))
('is fg', array([0.9970055 , 0.00299444], dtype=float32))
('is fg', array([0.9044132 , 0.09558681], dtype=float32))
('is fg', array([0.965164  , 0.03483604], dtype=float32))
(0.022982858, 0.00060292386)
-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([-0.01561795,  0.01534182,  0.01250567, -0.00470399], dtype=float32), array([151., 120., 199., 187.,   2.]))
0.9545454545454546
0.9518315546582059
0.92307692307

In [ ]:
import tensorflow as tf
tf.gather?